# Generated by Django 4.0.5 on 2022-06-05 21:00

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_listener'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='listener',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
