# Generated by Django 4.0.5 on 2022-06-05 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listener',
            options={'verbose_name': 'Listener', 'verbose_name_plural': 'Listeners'},
        ),
        migrations.AlterModelManagers(
            name='listener',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='listener',
            old_name='listen_user',
            new_name='user',
        ),
    ]
