# Generated by Django 4.0.5 on 2022-06-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_listener_options_alter_listener_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listener',
            name='track_list',
            field=models.ManyToManyField(null=True, to='base.track'),
        ),
    ]
